version: 2.1
orbs:
  # install node, and aws services
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  # the jobs
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in backend and frontend
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      # build the back-end and front-end apps
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build  
      # Deploy the back-end app, and upload the front-end file
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
# The workflow that orchestrate the jobs
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
      # Add filter to run only with changes made on main branch
        filters:
          branches:
            only:
              - main